version: "3.3"
services:
  ###############################################################################
  # Redis
  ###############################################################################
  # redis:
  #   logging:
  #     driver: 'syslog'
  #     options:
  #       syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
  #       tag: '{{.Name}}/{{.ID}}'
  #     #   syslog-facility: 'daemon'
  #   depends_on:
  #     - kibana
  redis:
  ###############################################################################
  # Mongo
  ###############################################################################
  # mongo:
  #   logging:
  #     driver: 'syslog'
  #     options:
  #       syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
  #       tag: '{{.Name}}/{{.ID}}'
  #     #   syslog-facility: 'daemon'
  #   depends_on:
  #     - kibana
  mongo:
    image: $ECR_REGISTRY/$ECR_REPOSITORY:mongo3.6
  ###############################################################################
  # NGINX
  ###############################################################################
  # nginx:
  #   logging:
  #     driver: 'syslog'
  #     options:
  #       syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
  #       tag: '{{.Name}}/{{.ID}}'
  #     #   syslog-facility: 'daemon'
  #   depends_on:
  #     - kibana
  nginx:
    image: $ECR_REGISTRY/$ECR_REPOSITORY:nginx1.17
  ###############################################################################
  # Authenticator
  ###############################################################################
  authenticator:
    build:
      image: $ECR_REGISTRY/$ECR_REPOSITORY/authenticator:$IMAGE_TAG
      context: .
      dockerfile: services/authenticator/Dockerfile
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
    #     tag: '{{.Name}}/{{.ID}}'
    # depends_on:
    #   - kibana
  ###############################################################################
  # PDFGenerator
  ###############################################################################
  pdfgenerator:
    build:
        image: $ECR_REGISTRY/$ECR_REPOSITORY/pdfgenerator:$IMAGE_TAG
      context: .
      dockerfile: services/pdfgenerator/Dockerfile
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
    #     tag: '{{.Name}}/{{.ID}}'
    # depends_on:
    #   - kibana
  ###############################################################################
  # Emailer
  ###############################################################################
  emailer:
    build:
      image: $ECR_REGISTRY/$ECR_REPOSITORY/emailer:$IMAGE_TAG
      context: .
      dockerfile: services/emailer/Dockerfile
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
    #     tag: '{{.Name}}/{{.ID}}'
    # depends_on:
    #   - kibana
  ###############################################################################
  # api
  ###############################################################################
  api:
    build:
      image: $ECR_REGISTRY/$ECR_REPOSITORY/api:$IMAGE_TAG
      context: .
      dockerfile: services/api/Dockerfile
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
    #     tag: '{{.Name}}/{{.ID}}'
    # depends_on:
    #   - kibana
  ###############################################################################
  # Frontend
  ###############################################################################
  frontend:
    build:
      image: $ECR_REGISTRY/$ECR_REPOSITORY/frontend:$IMAGE_TAG
      context: .
      dockerfile: webapps/landlord/Dockerfile
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
    #     tag: '{{.Name}}/{{.ID}}'
    # depends_on:
    #   - kibana
