version: "3.3"
services:
  redis:
    image: redis:latest
    volumes:
      - "./data/redis:/data"

  mongo:
    image: mongo:3.6
    volumes:
      - "./data/mongodb:/data/db"
    ports:
      - "$MONGO_PORT:$MONGO_PORT"

  nginx:
    image: nginx:1.17
    volumes:
      - ./config/nginx/etc/conf.d/prod.conf:/etc/nginx/conf.d/default.template
    command:
      - "bin/bash"
      - "-c"
      - "envsubst '$${NGINX_PORT},$${API_PORT},$${AUTHENTICATOR_PORT},$${FRONTEND_PORT},$${PDFGENERATOR_PORT},$${RESETSERVICE_PORT}' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && cat /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  authenticator:
    image: mre/authenticator:latest
    build:
      context: .
      dockerfile: services/authenticator/dev.Dockerfile
    volumes:
      - ./services/common:/usr/app/services/common
      - ./services/authenticator:/usr/app/services/authenticator
      - /usr/app/node_modules
      - /usr/app/services/authenticator/node_modules
    ports:
      - "$AUTHENTICATOR_DEBUG_PORT:9226"

  pdfgenerator:
    image: mre/pdfgenerator:latest
    build:
      context: .
      dockerfile: services/pdfgenerator/dev.Dockerfile
    volumes:
      - ./services/common:/usr/app/services/common
      - ./services/pdfgenerator:/usr/app/services/pdfgenerator
      - /usr/app/node_modules
      - /usr/app/services/pdfgenerator/node_modules
    ports:
      - "$PDFGENERATOR_DEBUG_PORT:9227"

  emailer:
    image: mre/emailer:latest
    build:
      context: .
      dockerfile: services/emailer/dev.Dockerfile
    volumes:
      - ./services/common:/usr/app/services/common
      - ./services/emailer:/usr/app/services/emailer
      - /usr/app/node_modules
      - /usr/app/services/emailer/node_modules
    ports:
      - "$EMAILER_DEBUG_PORT:9228"

  api:
    image: mre/api:latest
    build:
      context: .
      dockerfile: services/api/dev.Dockerfile
    volumes:
      - ./services/common:/usr/app/services/common
      - ./services/api:/usr/app/services/api
      - /usr/app/node_modules
      - /usr/app/services/api/node_modules
    ports:
      - "$API_DEBUG_PORT:9230"

  frontend:
    image: mre/frontend:latest
    build:
      context: .
      dockerfile: webapps/landlord/dev.Dockerfile
    volumes:
      - ./services/common:/usr/app/services/common
      - ./webapps/landlord:/usr/app/webapps/landlord
      - /usr/app/webapps/landlord/public
      - /usr/app/node_modules
      - /usr/app/webapps/landlord/node_modules
